book/urls.py
from django.urls import path
from .views import base_views, book_views, book_another_views
from .api import book_api, comment_api

app_name = "book"

urlpatterns = [
    # api
    path('slide-image/api/', book_api.SliderImageList.as_view()),
    path('endbook-list/api/', book_api.endBookList.as_view()),
    path('topbook-list/api/', book_api.TopBookList.as_view()),
    path('alltime-bestbook-list/api/', book_api.AllBestBook.as_view()),
    # base_views.py
    path('', base_views.index, name = 'index'),
    # book_veiws.py
    path('result/', book_views.searchResult, name = 'searchResult'),
    # book_another_views
    path('ending/', book_another_views.ending, name = "ending"),
    path('top100/', book_another_views.TopBook, name = "topbook"),
]

common/urls.py
from django.urls import path
from .api import user_api, signup_api, login_api
from .views import user_views, login_views,signup_views

app_name = "common"

urlpatterns = [
    # api
    path('users/api/', user_api.UserList.as_view()),
    path('login/api/', login_api.LoginApi.as_view()),
    path('<str:email>/api/', user_api.UserDetail.as_view()),
    path('resister/', signup_api.ResisterApi.as_view()),
    path('access_token/verify/', login_api.AccessTokenVeridate.as_view()),
    # login
    path('login/', login_views.login, name = "login"),
    # signup
    path('signup/', signup_views.signup, name='signup'),
    # user_views
    path('<str:email>/', user_views.userEdit, name = "userEdit"),
    path('user/<int:pk>/pwFind/', user_views.pwFind, name="pwFind"),
    path('<str:email>/library/', user_views.library, name="library"),
]

writeBook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
    path('book/', include('book.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

book/models.py
from pyexpat import model
from venv import create
from django.db import models
from common.models import Users
import datetime
# Create your models here.import datetime

DAYS_OF_WEEK = (
        ('mon', 'Monday'),
        ('tue', 'Tuesday'),
        ('wed', 'Wednesday'),
        ('thu', 'Thursday'),
        ('fri', 'Friday'),
        ('sat', 'Saturday'),
        ('sun', 'Sunday'),
    ) 

class Slider(models.Model):
    slide_image = models.ImageField(blank= True, null = True, upload_to= "images/")
   
class Books(models.Model):   
    title = models.CharField(max_length=30)
    author = models.ForeignKey(Users, on_delete=models.CASCADE, related_name='book_author')
    thumbnail = models.ImageField(null = False, blank = False, upload_to= "images/",)
    like_count = models.ManyToManyField(Users, related_name='book_like', blank = True)
    making = models.BooleanField(default=True)
    create_day_of_week = models.CharField(max_length=3, choices=DAYS_OF_WEEK)
    create_at = models.DateTimeField(auto_now_add = True)
    update_at = models.DateTimeField(auto_now = True)

class Episode(models.Model):
    book = models.ForeignKey(Books, on_delete=models.CASCADE)
    title = models.CharField(max_length= 50)
    content = models.TextField()
    create_at = models.DateTimeField(auto_now_add = True)

common/models.py
from pyexpat import model
from django.db import models
from django.contrib.auth.models import AbstractUser
from flask_sqlalchemy import models_committed
from sqlalchemy import null

# Create your models here.

class Users(AbstractUser):    
    username = models.CharField(max_length=30, unique=False)
    email = models.EmailField(unique=True, max_length=254)
    profile_image = models.ImageField(null = True, blank = True, upload_to= "images/", default="images/default-user.jpg")
    update_time = models.DateField(null = True, blank=True)
    nickname = models.CharField(max_length=20,null = True, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

book/views/base_views.py
from os import access
from django.http import JsonResponse
from django.shortcuts import render
from requests import Response
from common.models import Users
from ..models import *
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
import jwt, datetime
from writeBook.settings import SECRET_KEY
from rest_framework.decorators import permission_classes
from rest_framework.permissions import AllowAny, IsAuthenticated
import jwt, datetime
from writeBook.settings import SECRET_KEY, JWT_ALGORITHM

# @login_required(login_url="common:login")
@permission_classes([AllowAny])
def index(request):
    if request.method == "POST":
        access_token = request.headers.get('Authorization')

        decoded = jwt.decode(access_token, SECRET_KEY, JWT_ALGORITHM)
    return render(request, 'book/index.html')

book/views/book_another_views.py
from django.shortcuts import render

def ending(request):
    return render(request, 'book/endingBook.html')

def TopBook(request):
    return render(request, "book/topbook.html")

book/views/book_views.py
from django.shortcuts import render

def searchResult(request):
    return render(request, 'book/searchResult.html')

common/views/login_views.py
from django.http import HttpRequest
from django.shortcuts import redirect, render
from common.models import Users
from django.contrib import auth
from django.contrib.auth.decorators import login_required

def login(request):
    return render(request, 'common/login.html')  

def logout(request):
    auth.logout(request)
    return redirect("common:login")

common/views/signup_views.py
from django.shortcuts import redirect, render

def signup(request):
    return render(request, 'common/signup.html')

common/views/user_views.py
from django.shortcuts import redirect, render

def userEdit(request, email):
    if request.method == "POST":
        print(request.FILES['profile_image'])
    return render(request, 'common/userEdit.html')

def pwFind(request, pk):
    return render(request, 'common/pwFind.html')

def library(request, email):
    return render(request, 'common/library.html')

templates/book/endingBook.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="{% static 'css/ending.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    {%include 'navbar.html'%}
    ending

    <div class="endingbook_list">
        
    </div>

    <script src="{% static 'js/helper.js' %}"></script>
    <script src="{% static 'js/ending.js' %}"></script>
</body>
</html>

templates/book/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <title>Document</title>
</head>
<body>

    {% include 'navbar.html' %}

    <div class="index-page">
        
        <!-- 슬라이드 부분 -->
        <div class="slide-contents">

            <ul class="slide-input">
            </ul>
            
            <div class="slide-content-img">
            </div>

            <button class="slide-left"> < </button>
            <button class="slide-right"> > </button>

        </div>
        <!-- 책 부분 -->
        <main class="book-section">
            <div class="day_of_book-list">
                <ul class="week"> 
                    <li class=""><a href="#day" class="days" id="mon">월</a></li>
                    <li class=""><a href="#day" class="days" id="tue">화</a></li>
                    <li class=""><a href="#day" class="days" id="wed">수</a></li>
                    <li class=""><a href="#day" class="days" id="thu">목</a></li>
                    <li class=""><a href="#day" class="days" id="fri">금</a></li>
                    <li class=""><a href="#day" class="days" id="sat">토</a></li>
                    <li class=""><a href="#day" class="days" id="sun">일</a></li>
                </ul>

                <ul class="day_of_book_list">
                    
                    <li class="book">
                        <a href="#block" class="boot-tag">

                            <div class="book-image">
                                <img src="/media/images/user-image-icon-19_1lDgsmr.jpg" alt="/media/images/user-image-icon-19_1lDgsmr.jpg">
                            </div>

                            <div class="perbook-info">
                                <p class="book-title">죄송합니다용</p>

                                <div class="book-subinfo">
                                    <span class="author-nickname">박태준</span>
                                    <span class="book-like"><i class="fa fa-thumbs-up"></i> 9.99</span>
                                </div>
                            </div>


                        </a>
                    </li>
                    <!-- 2번째거 -->
                    <li class="book">
                        <a href="#block" class="book-tag">

                            <div class="book-image">
                                <img src="/media/images/chair-1.jpg" alt="/media/images/chair-1.jpg">
                            </div>

                            <div class="perbook-info">
                                <p class="book-title">죄송합니다용</p>

                                <div class="book-subinfo">
                                    <span class="author-nickname">기안84</span>
                                    <span class="book-like"><i class="fa fa-thumbs-up"></i> 9.99</span>
                                </div>
                            </div>


                        </a>
                    </li>
                    <!-- 3번째 거 -->
                    <li class="book">
                        <a href="#block" class="book-tag">

                            <div class="book-image">
                                <img src="/media/images/chair-2.jpg" alt="/media/images/chair-1.jpg">
                            </div>

                            <div class="perbook-info">
                                <p class="book-title">죄송합니다용</p>

                                <div class="book-subinfo">
                                    <span class="author-nickname">기안84</span>
                                    <span class="book-like"><i class="fa fa-thumbs-up"></i> 9.99</span>
                                </div>
                            </div>


                        </a>
                    </li>

                </ul>
            </div>
            <!-- 역대 최고 책 부분 -->
            <div class="most-list-book">
                <ul class="best-text">
                    <li class="best">역대 흥행작</li>
                </ul>

                <ul class="all-time-best-book-list">
                    <li class="best-book">
                        <a href="#" class="best-book-tag">

                            <div class="best-book-image">
                                <img src="/media/images/favicon.ico" alt="/media/images/favicon.ico">
                            </div>

                            <div class="best-book-info">
                                <span class="best-book-title">분노의 진형</span>
                                <span class="best-book-author">진형 02</span>
                            </div>

                        </a>
                    </li>
                    <!-- 2번째 베스트 책 -->
                    <li class="best-book">
                        <a href="#" class="best-book-tag">

                            <div class="best-book-image">
                                <img src="/media/images/head.jpg" alt="/media/images/head.jpg">
                            </div>

                            <div class="best-book-info">
                                <span class="best-book-title">분노의 로리충</span>
                                <span class="best-book-author">로리 02</span>
                            </div>

                        </a>
                    </li>

                </ul>

            </div>

        </main>

    </div>


    <script src="{% static 'js/helper.js' %}"></script>
    <script src="{% static 'js/index.js' %}"></script>
</body>
</html>

templates/book/library.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=\, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/library.css' %}">
    <title>Document</title>
</head>
<body>
    


    <script src="{% static 'js/library.js'%}"></script>
</body>
</html>

templates/book/searchResult.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/searchResult.css' %}">
    <title>Document</title>
</head>
<body>
    <h1>검색 결과를 받아보자</h1>

    <script src="{% static 'js/searchResult.js'%}"></script>
</body>
</html>

templates/book/topbook.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="{% static 'css/topbook.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    {% include 'navbar.html' %}
    <div class="topbook_list">

    </div>
    <script src="{% static 'js/helper.js' %}"></script>
    <script src="{% static 'js/topbook.js' %}"></script>
</body>
</html>

templates/common/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/login.css'%}">
    <title>Document</title>
</head>
<body>

    <div class="modals">
        <div class="modal">
            <span class="modal-close">X</span>

            <div class="modal-content">
                <div class="modal-user-email">fcripas8694@naver.com의 이메일로 인증번호가 발송 되었습니다.</div>
                <div class="status-mes"></div>
                <form action="#dasd" method="post" class="auth-number-form">
                    {%csrf_token%}
                    <input type="text" class="auth-number-input" placeholder="인증번호">
                    <button class="auth-btn">인증하기</button>
                </form>
            </div>

        </div>
    </div>

    <div class="login-box">
        <div class="title-logo">
            Write Book
        </div>
        <div class="login-infobox">
            <form action="{% url 'common:login' %}" method="post" class="login-form">
                {% csrf_token %}
                <div class="input-section">
                    <input type="email" class="email" name="email" required placeholder="이메일">
                    <input type="password" class="password" name="password" required placeholder="비밀번호">
                </div>
                <div class="btn-section">
                    <input type="submit" value="로그인">
                </div>
            </form>
        </div>
        <div class="divide"></div>
        <div class="other-login">
            <a href="#" class="social-naver"> Naver로 로그인</a>
        </div>
        <div class="forget-password">
            <a href="#">비밀번호를 잊으셨나요?</a>
        </div>
    </div>

    <div class="ask-signup">
        <span class="check-signupask">계정이 없으신가요?</span>
        <a href="{% url 'common:signup'%}">회원가입</a>
    </div>
    
    <script src="{% static 'js/helper.js' %}"></script>
    <script src="{% static 'js/login.js' %}"></script>
</body>
</html>

templates/common/signup.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/signup.css'%}">
    <title>Document</title>
</head>
<body>

    <div class="signup-box">
        <div class="title-logo">
            Write Book
        </div>
        <p class="subtitle-logo">
            Write Book과 함께 나만의 책을 만들어 보세요.
        </p>

        <div class="other-login">
            <a href="#" class="social-naver"> Naver로 로그인</a>
        </div>

        <div class="divide"></div>
        <div class="signup-infobox">
            <form action="#" method="post" class="signup-form">
                {% csrf_token %}
                <div class="input-section">
                    <input type="email" class="email" name="email" required placeholder="이메일">
                    <input type="text" class="username" name="username" required placeholder="이름">
                    <input type="text" class="nickname" name="nickname" required placeholder="닉네임">
                    <input type="password" class="password" name="password" required placeholder="비밀번호">
                </div>
                <div class="btn-section">
                    <input type="submit" value="회원가입">
                </div>
            </form>
        </div>
    </div>

    <div class="ask-login">
        <span class="check-loginask">계정이 있으신가요?</span>
        <a href="{% url 'common:login'%}">로그인</a>
    </div>

    <script src="{% static 'js/helper.js' %}"></script>
    <script src="{% static 'js/signup.js'%}"></script>
</body>
</html>

templates/common/userEdit.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/userEdit.css'%}">
    <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <title>Document</title>
</head>
<body>    

    <nav class="nav">    
        <div class="nav-first">

            <span class="logo"><a href="{% url 'book:index'%}"> WB <i class="fa fa-book"></i> </a></span>

            <div class="user-info-section">
                <button class="user-profile">
                    <i class="fa fa-user"></i>
                </button>

                <ul class="options">
                    <li><a href="#"><i class="fa fa-power-off"></i> 로그아웃 </a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="user-page-box">
        <section class="user-infoamtion-box">

            <div class="user-avatar">
                <form action="#" method="post">
                    {% csrf_token %}

                </form>
            </div>

            <div class="user-username">

            </div>

            

        </section>
    </div>

    <script src="{% static 'js/useredit.js' %}"></script>
    <script src="{% static 'js/helper.js'%}"></script>
</body>
</html>

templates/infomations.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="userId none">
        {{request.user.id}}
    </div>
</body>
</html>

templates/navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <title>Document</title>    
</head>
<body>

    <nav class="nav">    
        <div class="nav-first">

            <span class="logo"><a href="{% url 'book:index'%}"> WB <i class="fa fa-book"></i> </a></span>

            <div class="book-search-section">
                <form action="{% url 'book:index' %}" method="get" class="book-search-form">
                    <input type="search" name="result" id="search-id" placeholder="책 제목 검색" class="search-input">
                    <button class="search-btn"><i class="fa fa-search"></i></button>
                </form>
            </div>

            <div class="user-info-section">
                <button class="user-profile">
                    <i class="fa fa-user"></i>
                </button>

                <ul class="options">
                    <li><a href="#"><i class="fa fa-power-off"></i> 로그아웃 </a></li>
                </ul>
            </div>
        </div>

        <ul class="nav-second">
            <li class="ing-book"><a href="{% url 'book:index'%}">연재</a></li>
            <li><a href="{% url 'book:ending' %}">완결</a></li>
            <li><a href="{% url 'book:topbook'%}">Top 100</a></li>
        </ul>

    </nav>
</body>
</html>

templates/practice.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    try

    <form action="{% url 'book:practice'%}" method="post">
        {% csrf_token %}
        <input type="file" name="upload">
        <input type="submit" value="click">
    </form>

</body>
</html>